name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2025-06-06
          target: wasm32-wasip1-threads

      - name: Build project
        run: |
          sh ./run.sh
          cd sample/
          npm install
          mv node_modules depend
          mv depend/vscode-web/dist/node_modules depend/vscode-web/dist/depend

      - name: Patch product.json for GitHub Pages
        run: |
          cd sample/
          sed -i 's|"scheme": "http"|"scheme": "https"|g' product.json
          sed -i 's|"authority": "localhost:8080"|"authority": "yportne13.github.io"|g' product.json
          sed -i 's|"/myExt"|"/dependent-type-web-lsp/myExt"|g' product.json
          sed -i 's|"/TyportHDL"|"/dependent-type-web-lsp/TyportHDL"|g' product.json
          sed -i 's|"/wasm-wasi-core"|"/dependent-type-web-lsp/wasm-wasi-core"|g' product.json
          sed -i 's|"/vim"|"/dependent-type-web-lsp/vim"|g' product.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sample
          publish_branch: pages-github
